services:
  - type: web
    name: fpt-checkuniform
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000